### PR TITLE
[#45] DRF: Model with blank=True leads to error in serializer.EnumChoiceField

### LINKED ISSUE #45: DRF: Model with blank=True leads to error in serializer.EnumChoiceField
When setting `blank=True` in a model, the serializer implicitly inherits a serializer field with `allow_blank=True`. This, however, is being rejected by `django_enum_choices.serializers.EnumChoiceField` as an unknown argument in the `__init__` call (since it only inherits from the regular `serializers.Field`).

The work around I applied in my code is to add `allow_blank` to dump_kwargs [here](https://github.com/HackSoftware/django-enum-choices/blob/master/django_enum_choices/serializers.py#L101)

Do you agree this is the preferred solution? If so, I'm willing to submit a PR for it.

From an API perspective, I think it would be nicer to not need to specify blank=True at all (since you can derive that from the enum itself). However, it is needed as the admin menu of this model doesn't allow setting empty strings as the field on the admin menu form is marked as `required=True` otherwise. This might be a different discussion though.

### PR DESCRIPTION
**Pull request by SaturnFromTitan**
closes #45

### CODE REVIEW

**Comment by SaturnFromTitan** [comment]
@slavov-v How come the CI tests aren't executed?

All tests fail locally (no idea why - I never used tox before) and I just wanted to use the CI to see if my test is failing 😄

**Comment by slavov-v** [comment]
> @slavov-v How come the CI tests aren't executed?
> 
> All tests fail locally (no idea why - I never used tox before) and I just wanted to use the CI to see if my test is failing

We haven't set up the CI to run builds for PRs from forks.

Locally you need to have all versions of Python that `tox` uses to run the tests.
I personally use `pyenv` and set it up by running:
```
pyenv local 3.5.2 3.6.7 3.7.0
tox
```
I ran the tests from your fork locally, they're all passing.
Anyway, we enabled the CI for PRs from forks, so it should be triggered on your next commit :thinking:

**Comment by SaturnFromTitan** [comment]
I managed the get the test failing & resolved it now with my code change. Please have another look when you get the chance @slavov-v 

I didn't get the tests working locally though, but that's a different issue.

**Comment by slavov-v** [comment]
Looks good, merging it

**Pull request merged**
